### ISSUE TITLE
When I do pip3 install -r requirements.txt, I get an error about not finding a dependency

### ISSUE THREAD

**Issue by q2dg** [abrignoni/RLEAPP#107]
Specifically, this:

_ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14_

Thanks!

**Comment by abrignoni** [comment]
Added  python-magic-bin per distribution. Update and do pip install again.
