### ISSUE TITLE
chaseReturnsRTL.py broken

### ISSUE THREAD

**Issue by ramseys1990** [abrignoni/RLEAPP#207]
Currently chaseReturnsRTL.py is broken.  PyPDF2 has deprecated several functions used AND the format has now changed for the returns (at least for my current return).

I am currently working on fixing it as time permits and will create a pull request once I am done.

**Comment by abrignoni** [comment]
Thank you so much!!!
I don't have a current return so your fixes will be gratefully appreciated.

**Comment by ramseys1990** [comment]
This has been addressed here: #205

**Comment by stark4n6** [comment]
@ramseys1990 looks like this was merged, want to close the issue out?

**Comment by ramseys1990** [comment]
> @ramseys1990 looks like this was merged, want to close the issue out?

Sounds good!  Done!
