### ISSUE TITLE
Add support for Apple/iCloud GDPR zip files!

### ISSUE THREAD

**Issue by upintheairsheep** [abrignoni/RLEAPP#79]
Apple has a GDPR export feature on their [privacy website](http://privacy.apple.com/) that allows you do download some of your data. The zip files are separately exported and downloaded. I emailed you a zip file with all the zip files of iCloud apple GDPR zips minus the photos and iCloud Drive because otherwise it would be TOO BIG. So create a dummy account to get the data.

**Comment by upintheairsheep** [comment]
![Uploading CAB844FA-EE97-42E4-8FEC-ED3457D63DFA.png…]()

**Comment by upintheairsheep** [comment]
![A655B9AC-81F7-4865-BAAF-89AF46CEB27C](https://user-images.githubusercontent.com/43690204/155870367-f822bbd7-b23c-4758-894d-a2401fc65499.png)

**Comment by upintheairsheep** [comment]
Also I did not have any wallet data

**Comment by abrignoni** [comment]
Did not receive any email with exemplar data.
